# Generated by Django 2.0.3 on 2019-03-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosisApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='code_type',
            field=models.CharField(default='icd-10', max_length=7),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis_code',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterModelTable(
            name='diagnosis',
            table=None,
        ),
    ]
