# Generated by Django 2.0.3 on 2019-03-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosisApi', '0002_auto_20190302_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
